In [93]:
import pandas as pd
import numpy as np
import openpyxl as op
import sys
sys.path.append(r"C:\\Users\\Garimahdi.Supandi\\Hexindo Case")
import reportCompiler as rc
pd.set_option('display.max_columns',None)

from openpyxl import load_workbook

In [95]:
path = r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\Raw Data PelTo\raw_mar_26.xlsx"
preview = op.load_workbook(
        path,
        read_only = 'True',
        keep_links = False
)
sheetNames = list(preview.sheetnames)
print(pd.Series(sheetNames))

0     Accounting by Month DetAccUse
1           Accounting by Month Mod
2           Accounting by Month Dev
3        Accounting by Month DevMod
4        Accounting by Month DetDev
5     Accounting by Month DetDevOrg
6     Accounting by Month DetDevUse
7           Accounting by Month Org
8        Accounting by Month OrgMod
9        Accounting by Month DetOrg
10    Accounting by Month DetOrgDev
11          Accounting by Month Use
12       Accounting by Month UseMod
13       Accounting by Month DetUse
14    Accounting by Month DetUseDev
15            Accounting Month Data
16                           Sheet1
dtype: object

In [96]:
df_pelto = pd.read_excel(path, sheet_name = sheetNames[15])
df_pelto.head()

,03/2026,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,Organization Name,User Name,Unique Alphanumeric ID,User,Model Code_Identification ID,Device Name,Service Type,Output Color,Size,Model Name,AccountID,Impressions,Sheets,Actual Paper Reduction,Possible Paper Reduction,Jobs
1,Unknown,0000,Unknown,0000,JLTC101673_383472,Lt 3 Holding Barat Pasoso TKIS,Print,B/W,A4,FUJIFILM Apeos C3570,-,9,9,0,6,0
2,Unknown,0000,Unknown,0000,JLTC101673_383472,Lt 3 Holding Barat Pasoso TKIS,Print,Full Color,A4,FUJIFILM Apeos C3570,-,13,13,0,8,4
3,Unknown,0000,Unknown,0000,JLTC101673_383028,Lt 5 Holding Barat Pasoso SDM,Print,B/W,A4,FUJIFILM Apeos C3570,-,2,2,0,0,2
4,Unknown,0000,Unknown,0000,JLTC101673_383028,Lt 5 Holding Barat Pasoso SDM,Print,Full Color,A4,FUJIFILM Apeos C3570,-,41,41,0,29,3

In [97]:
newCols = df_pelto.iloc[0].values
cols = list(df_pelto.columns)
for o,n in zip(cols, newCols):
    df_pelto.rename(columns={o:n}, inplace=True)
df_pelto.columns

Index(['Organization Name', 'User Name', 'Unique Alphanumeric ID', 'User',
       'Model Code_Identification ID', 'Device Name', 'Service Type',
       'Output Color', 'Size', 'Model Name', 'AccountID', 'Impressions',
       'Sheets', 'Actual Paper Reduction', 'Possible Paper Reduction', 'Jobs'],
      dtype='object')

In [98]:
df_pelto.drop(index=0, axis=0, inplace=True)
df_pelto.head()

,Organization Name,User Name,Unique Alphanumeric ID,User,Model Code_Identification ID,Device Name,Service Type,Output Color,Size,Model Name,AccountID,Impressions,Sheets,Actual Paper Reduction,Possible Paper Reduction,Jobs
1,Unknown,0000,Unknown,0000,JLTC101673_383472,Lt 3 Holding Barat Pasoso TKIS,Print,B/W,A4,FUJIFILM Apeos C3570,-,9,9,0,6,0
2,Unknown,0000,Unknown,0000,JLTC101673_383472,Lt 3 Holding Barat Pasoso TKIS,Print,Full Color,A4,FUJIFILM Apeos C3570,-,13,13,0,8,4
3,Unknown,0000,Unknown,0000,JLTC101673_383028,Lt 5 Holding Barat Pasoso SDM,Print,B/W,A4,FUJIFILM Apeos C3570,-,2,2,0,0,2
4,Unknown,0000,Unknown,0000,JLTC101673_383028,Lt 5 Holding Barat Pasoso SDM,Print,Full Color,A4,FUJIFILM Apeos C3570,-,41,41,0,29,3
5,Unknown,0000,Unknown,0000,JLTC101673_383473,Lt 7 Holding Timur Pasoso PIP,Copy,Full Color,A3,FUJIFILM Apeos C3570,-,1,1,0,0,1

In [99]:
cols = list(df_pelto.columns)

In [100]:
df_pelto[cols[4]] = df_pelto[cols[4]].apply(lambda x:x.split('_'))
newTemp = ['Model Code','Serial Number']
for i,nt in enumerate(newTemp):
    df_pelto[nt] = df_pelto[cols[4]].apply(lambda x:x[i])
df_pelto = df_pelto[['Organization Name', 'User Name', 'Unique Alphanumeric ID', 'User',
       'Model Code','Serial Number', 'Device Name', 'Service Type',
       'Output Color', 'Size', 'Model Name', 'AccountID', 'Impressions',
       'Sheets', 'Actual Paper Reduction', 'Possible Paper Reduction', 'Jobs']]
df_pelto.head(2)

,Organization Name,User Name,Unique Alphanumeric ID,User,Model Code,Serial Number,Device Name,Service Type,Output Color,Size,Model Name,AccountID,Impressions,Sheets,Actual Paper Reduction,Possible Paper Reduction,Jobs
1,Unknown,0000,Unknown,0000,JLTC101673,383472,Lt 3 Holding Barat Pasoso TKIS,Print,B/W,A4,FUJIFILM Apeos C3570,-,9,9,0,6,0
2,Unknown,0000,Unknown,0000,JLTC101673,383472,Lt 3 Holding Barat Pasoso TKIS,Print,Full Color,A4,FUJIFILM Apeos C3570,-,13,13,0,8,4

In [101]:
df_pelto['Serial Number'].unique()
len(df_pelto['Serial Number'].unique())

20

In [102]:
# Mapping SN with EQ
reference = pd.read_excel(
    r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\new_ref_machine.xlsx",
    sheet_name = 'latest',
    dtype={'Serial Number':str}
)
reference

,Serial Number,Model Name,Device Name
0,010722,FUJIFILM Apeos C3530,Pelindo Tower Lt.18 Sekretaris Direksi Wadirut
1,010723,FUJIFILM Apeos C3530,Pelindo Tower Lt.18 Sekretaris Direksi Dir SDM
2,010724,FUJIFILM Apeos C3530,Pelindo Tower Lt.18 Sekretaris Direksi Dirut
3,010725,FUJIFILM Apeos C3530,Pelindo Tower Lt.18 Sekretaris Direksi Dir Pen...
4,383028,FUJIFILM Apeos C3570,Lt 5 Holding Barat Pasoso SDM
5,383274,FUJIFILM Apeos C3570,Pelindo Tower Lt.20 Utara
6,383275,FUJIFILM Apeos C3570,Pelindo Tower Lt.20 Selatan
7,383329,FUJIFILM Apeos C3570,Pelindo Tower Lt.17 Typical (P1)
8,383330,FUJIFILM Apeos C3570,Pelindo Tower Lt.17 Typical (P2)
9,383332,FUJIFILM Apeos C3570,Pelindo Tower Lt.17 VIP (P1)
10,383471,FUJIFILM Apeos C3570,Lt 6 Holding Barat Pasoso SPI
11,383472,FUJIFILM Apeos C3570,Lt 3 Holding Barat Pasoso TKIS
12,383473,FUJIFILM Apeos C3570,Lt 7 Holding Timur Pasoso PIP
13,383283,FUJIFILM Apeos C3570,Kantor site Proyek Terminal Petikemas Kalibaru...
14,383474,FUJIFILM Apeos C3570,Lt 4 Holding Barat Pasoso SSC
15,383475,FUJIFILM Apeos C3570,Lt 4 Holding Timur Pasoso Keuangan-2
16,383481,FUJIFILM Apeos C3570,Cab Priok lt 7 Satker BMTH
17,834582,FUJI XEROX ApeosPort C3570,Pelindo Tower Lt.19 Timur
18,834583,FUJI XEROX ApeosPort C3570,Pelindo Tower Lt.19 Selatan
19,834584,FUJI XEROX ApeosPort C3570,Pelindo Tower Lt.21 Utara
20,834588,FUJI XEROX ApeosPort C3570,Pelindo Tower Lt.21 Selatan

In [103]:
#sn = dict(locMap[['Serial Number','EQ Number']].values)
#try to Open the Excel Files first (new_ref_machine.xlsx), before running the code block
snLoc = dict(reference[['Serial Number','Device Name']].values)
snLoc

{'010722': 'Pelindo Tower Lt.18 Sekretaris Direksi Wadirut',
 '010723': 'Pelindo Tower Lt.18 Sekretaris Direksi Dir SDM',
 '010724': 'Pelindo Tower Lt.18 Sekretaris Direksi Dirut',
 '010725': 'Pelindo Tower Lt.18 Sekretaris Direksi Dir Pengelola',
 '383028': 'Lt 5 Holding Barat Pasoso SDM',
 '383274': 'Pelindo Tower Lt.20 Utara',
 '383275': 'Pelindo Tower Lt.20 Selatan',
 '383329': 'Pelindo Tower Lt.17 Typical (P1)',
 '383330': 'Pelindo Tower Lt.17 Typical (P2)',
 '383332': 'Pelindo Tower Lt.17 VIP (P1)',
 '383471': 'Lt 6 Holding Barat Pasoso SPI',
 '383472': 'Lt 3 Holding Barat Pasoso TKIS',
 '383473': 'Lt 7 Holding Timur Pasoso PIP',
 '383283': 'Kantor site Proyek Terminal Petikemas Kalibaru Utara PT Pelindo, Tanjung Priok ',
 '383474': 'Lt 4 Holding Barat Pasoso SSC',
 '383475': 'Lt 4 Holding Timur Pasoso Keuangan-2',
 '383481': 'Cab Priok lt 7 Satker BMTH',
 '834582': 'Pelindo Tower Lt.19 Timur',
 '834583': 'Pelindo Tower Lt.19 Selatan',
 '834584': 'Pelindo Tower Lt.21 Utara',
 '834588': 'Pelindo Tower Lt.21 Selatan'}

In [104]:
df_pelto['Location'] = df_pelto['Serial Number'].map(snLoc)
df_pelto.loc[df_pelto['Location'].isna()]

Empty DataFrame
Columns: [Organization Name, User Name, Unique Alphanumeric ID, User, Model Code, Serial Number, Device Name, Service Type, Output Color, Size, Model Name, AccountID, Impressions, Sheets, Actual Paper Reduction, Possible Paper Reduction, Jobs, Location]
Index: []

In [86]:
df_pelto['Device Name'].unique()

array(['Device Name', 'Lt 3 Holding Barat Pasoso TKIS',
       'Lt 5 Holding Barat Pasoso SDM', 'Lt 7 Holding Timur Pasoso PIP',
       'Lt 6 Holding Barat Pasoso SPI', 'Lt 19 Timur',
       'Lt 17 - Typical (P1)', 'Lt 21 Utara', 'Lt 20 Selatan',
       'Lt 20 Utara', 'Lt 18 Dirut',
       'Lantai 4 Holding Pasoso Timur Keuangan-2', 'Lt 19 Selatan',
       'Lt 21 Selatan', 'Pelto lt 18 Sekdir Pengelola',
       'Lt 17 - VIP (P1)', 'Lt 17 - Typical (P2)',
       'Pelto lt 18 Sekdir Wadirut', 'Lt 18 - Dir SDM',
       'Cab Priok lt 7 Satker BMTH', 'Lt 4 Holding Barat Pasoso SSC'],
      dtype=object)

# Location revisions (06/01/2025):

1) Pelto lt 18 Sekdir Pengelola --> Lt 18 - Dir Pengelola
2) Lantai 4 Holding Pasoso Timur Keuangan-2 --> Lantai 4 Timur Keuangan-2

In [105]:
piv_df_pelto = pd.pivot_table(
    data = df_pelto,
    index=['Serial Number','Model Name','Location'],
    columns='Output Color',
    values='Impressions',
    aggfunc='sum'
)

In [106]:
piv_df_pelto['Full Color'].fillna(0, inplace=True)
piv_df_pelto['2-Color'].fillna(0, inplace=True)
piv_df_pelto

,,Output Color,B/W,Full Color
Serial Number,Model Name,Location,,
010722,FUJIFILM Apeos C3530,Pelindo Tower Lt.18 Sekretaris Direksi Wadirut,15,26
010723,FUJIFILM Apeos C3530,Pelindo Tower Lt.18 Sekretaris Direksi Dir SDM,4,279
010724,FUJIFILM Apeos C3530,Pelindo Tower Lt.18 Sekretaris Direksi Dirut,107,1113
010725,FUJIFILM Apeos C3530,Pelindo Tower Lt.18 Sekretaris Direksi Dir Pengelola,203,2023
383028,FUJIFILM Apeos C3570,Lt 5 Holding Barat Pasoso SDM,104,182
383274,FUJIFILM Apeos C3570,Pelindo Tower Lt.20 Utara,2392,3723
383275,FUJIFILM Apeos C3570,Pelindo Tower Lt.20 Selatan,3263,2089
383329,FUJIFILM Apeos C3570,Pelindo Tower Lt.17 Typical (P1),219,1457
383330,FUJIFILM Apeos C3570,Pelindo Tower Lt.17 Typical (P2),133,1206
383332,FUJIFILM Apeos C3570,Pelindo Tower Lt.17 VIP (P1),45,2004
383471,FUJIFILM Apeos C3570,Lt 6 Holding Barat Pasoso SPI,89,2099
383472,FUJIFILM Apeos C3570,Lt 3 Holding Barat Pasoso TKIS,27,70
383473,FUJIFILM Apeos C3570,Lt 7 Holding Timur Pasoso PIP,126,619
383474,FUJIFILM Apeos C3570,Lt 4 Holding Barat Pasoso SSC,24,99
383475,FUJIFILM Apeos C3570,Lt 4 Holding Timur Pasoso Keuangan-2,20,104
383481,FUJIFILM Apeos C3570,Cab Priok lt 7 Satker BMTH,175,251
834582,FUJI XEROX ApeosPort C3570,Pelindo Tower Lt.19 Timur,347,974
834583,FUJI XEROX ApeosPort C3570,Pelindo Tower Lt.19 Selatan,906,2006
834584,FUJI XEROX ApeosPort C3570,Pelindo Tower Lt.21 Utara,481,3095
834588,FUJI XEROX ApeosPort C3570,Pelindo Tower Lt.21 Selatan,358,1792

In [107]:
piv_df_pelto.shape

(20, 2)

In [108]:
piv_df_pelto.to_excel(
    "D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\Laporan ILCS\Pre-Summary mar testyy 2026.xlsx"
)

# Run underneath if necessary.

In [ ]:
sn_510310 =  pd.read_csv(
    r"C:\Users\Garimahdi.Supandi\Downloads\HistoryMeter.csv",
    encoding = 'latin-1'
)
sn_510310.info()

In [ ]:
sn_510310.head()

In [ ]:
sn_510310['log_date'] = sn_510310['log_date'].apply(lambda x:x.split('T'))
sn_510310['Date'] = sn_510310['log_date'].apply(lambda x:x[0])
sn_510310['Time'] = sn_510310['log_date'].apply(lambda x:x[1])
sn_510310.drop(columns='log_date', axis=1, inplace=True)
sn_510310['Date'] = sn_510310['Date'].apply(lambda x:x.replace('-','/'))
sn_510310.head()

In [ ]:
sn_510310.to_excel("C:\\Users\\Garimahdi.Supandi\\Downloads\\HistoryMeter_510310.xlsx")

In [ ]:
aug_510310 = rc.dateFilter(sn_510310,8,6,31,30)
aug_510310

In [ ]:
print((531+944)/2)

# Reengineer the data due to copier swaps.

In [ ]:
df_pelto.info()

In [ ]:
user_devs = df_pelto.groupby(['User Name','Device Name','Model Name','Service Type','Output Color','Size'])['Impressions'].sum().reset_index()
user_devs

In [ ]:
cc = user_devs.loc[(user_devs['Device Name']=='Lantai 4 Timur Keuangan-2') & (user_devs['Model Name']=='FUJI XEROX DocuCentre-VII C3373')]
cc.shape

In [ ]:
user_devs_rev = user_devs.loc[
    (user_devs['Device Name']!='Lantai 4 Timur Keuangan-2') | (user_devs['Model Name']!='FUJI XEROX DocuCentre-VII C3373')
]

user_devs_rev.shape

In [ ]:
dd = user_devs_rev.loc[(user_devs['Device Name']=='Lantai 4 Timur Keuangan-2') & (user_devs['Model Name']=='FUJIFILM Apeos C3570')]

In [ ]:
dd['Impressions'].sum()

In [ ]:
path = r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\Laporan ILCS\Pre-Summary Desember 2024 - Copy.xlsx"
class excelReader:
    def __init__(self,file):
        self.file = file
    def sheetChecker(self):
        sc = pd.ExcelFile(self.file)
        print(sc.sheet_names)
    def sheetSelector(self,sheetName):
        df = pd.read_excel(self.file, sheet_name=sheetName)
        return df

reader = excelReader(path)
reader.sheetChecker()
summary = reader.sheetSelector('Summary')
details = reader.sheetSelector('Details')
print(summary.shape)
print(details.shape)

In [ ]:
with pd.ExcelWriter(path) as writer:
    summary.to_excel(writer,sheet_name='Summary',index=False)
    user_devs_rev.to_excel(writer, sheet_name='Details',index=False)