In [1]:
import pandas as pd
import numpy as np
from openpyxl import load_workbook
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

import sys
sys.path.append(r"C:\\Users\\Garimahdi.Supandi\\Hexindo Case")
import reportCompiler as rc

In [2]:
df_5mo = pd.read_csv(
    r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\Laporan ILCS\ILCS_all.csv",
    encoding = 'utf-8'
)
d = list(df_5mo.columns)
df_5mo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Lokasi        28 non-null     object
 1   SN            28 non-null     int64
 2   EQ            28 non-null     int64
 3   Mono Pages    28 non-null     int64
 4   Colour Pages  28 non-null     int64
 5   Periode       28 non-null     object
dtypes: int64(4), object(2)
memory usage: 1.4+ KB

In [3]:
df_5mo

                 Lokasi      SN      EQ  Mono Pages  Colour Pages Periode
0   Pelindo Tower Lt.20  834582  807628         166          1704     Jan
1   Pelindo Tower Lt.20  834583  807629         384          2637     Jan
2   Pelindo Tower Lt.19  834584  807630        2446          4666     Jan
3   Pelindo Tower Lt.19  834588  807634         459          1322     Jan
4       Jl. Pasoso Lt.6  383028  807439         240           624     Jan
5       Jl. Pasoso No.1  337981  762463           0             0     Jan
6   Pelindo Tower Lt.20  834582  807628         738          2358     Feb
7   Pelindo Tower Lt.20  834583  807629         534          1949     Feb
8   Pelindo Tower Lt.19  834584  807630         599          2178     Feb
9   Pelindo Tower Lt.19  834588  807634         334          1639     Feb
10      Jl. Pasoso Lt.6  383028  807439         285           786     Feb
11      Jl. Pasoso No.1  337981  762463          17           255     Feb
12  Pelindo Tower Lt.20  834582  807628         434          2153     Mar
13  Pelindo Tower Lt.20  834583  807629        1344          1981     Mar
14  Pelindo Tower Lt.19  834584  807630         326          1585     Mar
15  Pelindo Tower Lt.19  834588  807634         458          3137     Mar
16      Jl. Pasoso Lt.6  383028  807439         285           730     Mar
17      Jl. Pasoso No.1  337981  762463           0             0     Mar
18  Pelindo Tower Lt.20  834582  807628         362          1609     Apr
19  Pelindo Tower Lt.20  834583  807629        1244          1544     Apr
20  Pelindo Tower Lt.19  834584  807630         553          2449     Apr
21  Pelindo Tower Lt.19  834588  807634         561          1442     Apr
22      Jl. Pasoso Lt.6  383028  807439         115           597     Apr
23  Pelindo Tower Lt.20  834582  807628         221           540     Mei
24  Pelindo Tower Lt.20  834583  807629         357          1179     Mei
25  Pelindo Tower Lt.19  834584  807630         369           535     Mei
26  Pelindo Tower Lt.19  834588  807634         190           765     Mei
27      Jl. Pasoso Lt.6  383028  807439         146           418     Mei

In [4]:
df_test = df_5mo.loc[df_5mo[d[5]] == 'Jan']
df_test

                Lokasi      SN      EQ  Mono Pages  Colour Pages Periode
0  Pelindo Tower Lt.20  834582  807628         166          1704     Jan
1  Pelindo Tower Lt.20  834583  807629         384          2637     Jan
2  Pelindo Tower Lt.19  834584  807630        2446          4666     Jan
3  Pelindo Tower Lt.19  834588  807634         459          1322     Jan
4      Jl. Pasoso Lt.6  383028  807439         240           624     Jan
5      Jl. Pasoso No.1  337981  762463           0             0     Jan

In [5]:
try:
    #df_test['temp'] = df_test[[d[3],d[4]]].apply(lambda x,y:([x,y]))
    df_test['temp'] = list(zip(df_test[d[3]],df_test[d[4]]))
except Exception as e:
    print(e)

print(zip(df_test[d[3]],df_test[d[4]]))

<zip object at 0x000001CC22DD6000>

C:\Users\Garimahdi.Supandi\AppData\Local\Temp\ipykernel_17932\2213014006.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['temp'] = list(zip(df_test[d[3]],df_test[d[4]]))

In [6]:
df_test['temp'] = df_test['temp'].apply(lambda x: list(x))
df_test

C:\Users\Garimahdi.Supandi\AppData\Local\Temp\ipykernel_17932\1188650498.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['temp'] = df_test['temp'].apply(lambda x: list(x))

,Lokasi,SN,EQ,Mono Pages,Colour Pages,Periode,temp
0,Pelindo Tower Lt.20,834582,807628,166,1704,Jan,"[166, 1704]"
1,Pelindo Tower Lt.20,834583,807629,384,2637,Jan,"[384, 2637]"
2,Pelindo Tower Lt.19,834584,807630,2446,4666,Jan,"[2446, 4666]"
3,Pelindo Tower Lt.19,834588,807634,459,1322,Jan,"[459, 1322]"
4,Jl. Pasoso Lt.6,383028,807439,240,624,Jan,"[240, 624]"
5,Jl. Pasoso No.1,337981,762463,0,0,Jan,"[0, 0]"

In [7]:
df_test = df_test.set_index(d[2])
df_test

,Lokasi,SN,Mono Pages,Colour Pages,Periode,temp
EQ,,,,,,
807628,Pelindo Tower Lt.20,834582,166,1704,Jan,"[166, 1704]"
807629,Pelindo Tower Lt.20,834583,384,2637,Jan,"[384, 2637]"
807630,Pelindo Tower Lt.19,834584,2446,4666,Jan,"[2446, 4666]"
807634,Pelindo Tower Lt.19,834588,459,1322,Jan,"[459, 1322]"
807439,Jl. Pasoso Lt.6,383028,240,624,Jan,"[240, 624]"
762463,Jl. Pasoso No.1,337981,0,0,Jan,"[0, 0]"

In [8]:
d[5]

'Periode'

In [9]:
idx_rep = df_test.index.repeat(df_test['temp'].str.len(), axis = None)
rep = pd.DataFrame({'Impressions':np.concatenate(df_test['temp'].values)},index = idx_rep)
rep

        Impressions
EQ
807628          166
807628         1704
807629          384
807629         2637
807630         2446
807630         4666
807634          459
807634         1322
807439          240
807439          624
762463            0
762463            0

In [10]:
rep['Type'] = ['Mono','Colour','Mono','Colour','Mono','Colour','Mono','Colour','Mono','Colour','Mono','Colour']
rep

        Impressions    Type
EQ
807628          166    Mono
807628         1704  Colour
807629          384    Mono
807629         2637  Colour
807630         2446    Mono
807630         4666  Colour
807634          459    Mono
807634         1322  Colour
807439          240    Mono
807439          624  Colour
762463            0    Mono
762463            0  Colour

# Update code: JLA Raw Data

In [11]:
preview = load_workbook(
    r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\12_2023.xlsx",
    read_only = True,
    keep_links = False
)
print(list(preview.sheetnames))

['Accounting by Month DetAccUse', 'Accounting by Month Mod', 'Accounting by Month Dev', 'Accounting by Month DevMod', 'Accounting by Month DetDev', 'Accounting by Month DetDevOrg', 'Accounting by Month DetDevUse', 'Accounting by Month Org', 'Accounting by Month OrgMod', 'Accounting by Month DetOrg', 'Accounting by Month DetOrgDev', 'Accounting by Month Use', 'Accounting by Month UseMod', 'Accounting by Month DetUse', 'Accounting by Month DetUseDev', 'Accounting Month Data', 'Sheet1']

In [12]:
preview_head = pd.read_excel(
    r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\12_2023.xlsx",
    sheet_name = 'Accounting Month Data'
)
preview_head.head()

,12/2023,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,Organization Name,User Name,Unique Alphanumeric ID,User,Model Code_Identification ID,Device Name,Service Type,Output Color,Size,Model Name,AccountID,Impressions,Sheets,Actual Paper Reduction,Possible Paper Reduction,Jobs
1,Unknown,0494,Unknown,0494,JLTC101673_383028,Apeos C3570,Print,B/W,A4,FUJIFILM Apeos C3570,-,6,6,0,0,6
2,Unknown,0494,Unknown,0494,JLTC101673_383028,Apeos C3570,Print,Full Color,A4,FUJIFILM Apeos C3570,-,2,2,0,0,2
3,Unknown,100378,Unknown,100378,JLTC101545_834584,ApeosPort C3570,Print,B/W,A4,FUJI XEROX ApeosPort C3570,-,1,1,0,0,1
4,Unknown,100378,Unknown,100378,JLTC101545_834584,ApeosPort C3570,Print,Full Color,A4,FUJI XEROX ApeosPort C3570,-,1,1,0,0,1

In [13]:
print(preview_head.iloc[0].values,'\n')
print(list(preview_head.columns),'\n')
old = list(preview_head.columns)
new = preview_head.iloc[0]

for i,j in zip(old,new):
    preview_head.rename(columns={i:j}, inplace=True)

print(list(preview_head.columns))
preview_head.drop(axis=0, index=0, inplace=True)
preview_head.head()
preview_head['Model Code_Identification ID'] = preview_head['Model Code_Identification ID'].apply(lambda x:x.split('_'))
preview_head.columns
#preview_head['Model Code'] = preview_head['Model Code_Identification ID'].apply(lambda x:x[0])

['Organization Name' 'User Name' 'Unique Alphanumeric ID' 'User'
 'Model Code_Identification ID' 'Device Name' 'Service Type'
 'Output Color' 'Size' 'Model Name' 'AccountID' 'Impressions' 'Sheets'
 'Actual Paper Reduction' 'Possible Paper Reduction' 'Jobs']

['12/2023', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15']

['Organization Name', 'User Name', 'Unique Alphanumeric ID', 'User', 'Model Code_Identification ID', 'Device Name', 'Service Type', 'Output Color', 'Size', 'Model Name', 'AccountID', 'Impressions', 'Sheets', 'Actual Paper Reduction', 'Possible Paper Reduction', 'Jobs']

Index(['Organization Name', 'User Name', 'Unique Alphanumeric ID', 'User',
       'Model Code_Identification ID', 'Device Name', 'Service Type',
       'Output Color', 'Size', 'Model Name', 'AccountID', 'Impressions',
       'Sheets', 'Actual Paper Reduction', 'Possible Paper Reduction', 'Jobs'],
      dtype='object')

In [14]:
preview_head['Model Code'] = preview_head['Model Code_Identification ID'].apply(lambda x:x[0])
preview_head['Identification ID'] = preview_head['Model Code_Identification ID'].apply(lambda x:x[1])
preview_head.drop(axis=1, columns='Model Code_Identification ID', inplace=True)
preview_head.head()

,Organization Name,User Name,Unique Alphanumeric ID,User,Device Name,Service Type,Output Color,Size,Model Name,AccountID,Impressions,Sheets,Actual Paper Reduction,Possible Paper Reduction,Jobs,Model Code,Identification ID
1,Unknown,0494,Unknown,0494,Apeos C3570,Print,B/W,A4,FUJIFILM Apeos C3570,-,6,6,0,0,6,JLTC101673,383028
2,Unknown,0494,Unknown,0494,Apeos C3570,Print,Full Color,A4,FUJIFILM Apeos C3570,-,2,2,0,0,2,JLTC101673,383028
3,Unknown,100378,Unknown,100378,ApeosPort C3570,Print,B/W,A4,FUJI XEROX ApeosPort C3570,-,1,1,0,0,1,JLTC101545,834584
4,Unknown,100378,Unknown,100378,ApeosPort C3570,Print,Full Color,A4,FUJI XEROX ApeosPort C3570,-,1,1,0,0,1,JLTC101545,834584
5,Unknown,100518,Unknown,100518,Apeos C3570,Print,B/W,A4,FUJIFILM Apeos C3570,-,6,6,0,1,5,JLTC101673,383274

In [15]:
preview_head['Period'] = 'Des 2023'
preview_head.head()

,Organization Name,User Name,Unique Alphanumeric ID,User,Device Name,Service Type,Output Color,Size,Model Name,AccountID,Impressions,Sheets,Actual Paper Reduction,Possible Paper Reduction,Jobs,Model Code,Identification ID,Period
1,Unknown,0494,Unknown,0494,Apeos C3570,Print,B/W,A4,FUJIFILM Apeos C3570,-,6,6,0,0,6,JLTC101673,383028,Des 2023
2,Unknown,0494,Unknown,0494,Apeos C3570,Print,Full Color,A4,FUJIFILM Apeos C3570,-,2,2,0,0,2,JLTC101673,383028,Des 2023
3,Unknown,100378,Unknown,100378,ApeosPort C3570,Print,B/W,A4,FUJI XEROX ApeosPort C3570,-,1,1,0,0,1,JLTC101545,834584,Des 2023
4,Unknown,100378,Unknown,100378,ApeosPort C3570,Print,Full Color,A4,FUJI XEROX ApeosPort C3570,-,1,1,0,0,1,JLTC101545,834584,Des 2023
5,Unknown,100518,Unknown,100518,Apeos C3570,Print,B/W,A4,FUJIFILM Apeos C3570,-,6,6,0,1,5,JLTC101673,383274,Des 2023

In [16]:
print(preview_head['Identification ID'].unique())
print(len(preview_head['Device Name'].unique()))
mapping = preview_head[['Identification ID','Device Name','Model Name']]
mapping.loc[mapping['Identification ID'] == '482065']

['383028' '834584' '383274' '834582' '834588' '482041' '834583' '482047'
 '510310' '482067' '482054' '482065']
7

    Identification ID          Device Name                       Model Name
294            482065  ApeosPort-VII C3370  FUJI XEROX DocuCentre-VII C3373
295            482065  ApeosPort-VII C3370  FUJI XEROX DocuCentre-VII C3373
296            482065  ApeosPort-VII C3370  FUJI XEROX DocuCentre-VII C3373
385            482065  ApeosPort-VII C3370  FUJI XEROX DocuCentre-VII C3373
386            482065  ApeosPort-VII C3370  FUJI XEROX DocuCentre-VII C3373
387            482065  ApeosPort-VII C3370  FUJI XEROX DocuCentre-VII C3373
390            482065  ApeosPort-VII C3370  FUJI XEROX DocuCentre-VII C3373
391            482065  ApeosPort-VII C3370  FUJI XEROX DocuCentre-VII C3373
435            482065  ApeosPort-VII C3370  FUJI XEROX DocuCentre-VII C3373
436            482065  ApeosPort-VII C3370  FUJI XEROX DocuCentre-VII C3373
437            482065  ApeosPort-VII C3370  FUJI XEROX DocuCentre-VII C3373
447            482065  ApeosPort-VII C3370  FUJI XEROX DocuCentre-VII C3373
448            482065  ApeosPort-VII C3370  FUJI XEROX DocuCentre-VII C3373

# Grouping each month

In [17]:
def groups(path, period):
    df = pd.read_excel(path, sheet_name='Accounting Month Data')
    
    old = list(df.columns)
    new = df.iloc[0]
    for i,j in zip(old,new):
        df.rename(columns={i:j}, inplace=True)
    
    df.drop(axis=0, index=0, inplace=True)
    df['Model Code_Identification ID'] = df['Model Code_Identification ID'].apply(lambda x:x.split('_'))
    
    df['Model Code'] = df['Model Code_Identification ID'].apply(lambda x:x[0])
    df['Identification ID'] = df['Model Code_Identification ID'].apply(lambda x:x[1])
    df.drop(axis=1, columns='Model Code_Identification ID', inplace=True)
    
    df['Period'] = period
    
    return df

In [18]:
sep_23 = groups(r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\09_2023.xlsx", 'Sep 2023')
oct_23 = groups(r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\10_2023.xlsx", 'Okt 2023')
nov_23 = groups(r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\11_2023.xlsx", 'Nov 2023')
des_23 = groups(r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\12_2023.xlsx", 'Des 2023')
jan_24 = groups(r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\01_2024.xlsx", 'Jan 2024')
feb_24 = groups(r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\02_2024.xlsx", 'Feb 2024')
mar_24 = groups(r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\03_2024.xlsx", 'Mar 2024')
apr_24 = groups(r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\04_2024.xlsx", 'Apr 2024')
may_24 = groups(r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\05_2024.xlsx", 'Mei 2024')
jun_24 = groups(r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\06_2024.xlsx", 'Jun 2024')
jul_24 = groups(r"D:\Astragraphia\BO1\Pelindo\Zweite Entwicklung\07_2024.xlsx", 'Jul 2024')

In [19]:
sn_loc = pd.read_csv(
    r"D:\\Astragraphia\\BO1\\Pelindo\\Zweite Entwicklung\\for_mapping.csv",
    dtype=str
)

sn_loc

sn_map = dict(sn_loc.values)
sn_map

{'510310': 'Lt 3 Holding Barat Pasoso TKIS',
 '834582': 'Lt 21 Utara',
 '834583': 'Lt 19 Selatan',
 '834584': 'Lt 19 Timur',
 '834588': 'Lt 21 Selatan',
 '482041': 'Lantai 4 Timur Keuangan-2',
 '482054': 'Lt 4 Holding Barat Pasoso SSC',
 '482065': 'Lt 7 Holding Timur Pasoso PIP',
 '482067': 'Lt 6 Holding Barat Pasoso SPI',
 '010722': 'Lt 18 - Wadirut',
 '010723': 'Lt 18 - Dir SDM',
 '010724': 'Lt 18 Dirut',
 '010725': 'Lt 18 - Dir Pengelola',
 '383028': 'Lt 5 Holding Barat Pasoso SDM',
 '383274': 'Lt 20 Utara',
 '383275': 'Lt 20 Selatan',
 '383329': 'Lt 17 -  Typical (P1)',
 '383330': 'Lt 17 - Typical (P2)',
 '383332': 'Lt 17 - VIP (P1)'}

In [20]:
sep_23['Location'] = sep_23['Identification ID'].map(sn_map)
oct_23['Location'] = oct_23['Identification ID'].map(sn_map)
nov_23['Location'] = nov_23['Identification ID'].map(sn_map)
des_23['Location'] = des_23['Identification ID'].map(sn_map)
jan_24['Location'] = jan_24['Identification ID'].map(sn_map)
feb_24['Location'] = feb_24['Identification ID'].map(sn_map)
mar_24['Location'] = mar_24['Identification ID'].map(sn_map)
apr_24['Location'] = apr_24['Identification ID'].map(sn_map)
may_24['Location'] = may_24['Identification ID'].map(sn_map)
jun_24['Location'] = jun_24['Identification ID'].map(sn_map)
jul_24['Location'] = jul_24['Identification ID'].map(sn_map)

In [21]:
gr_sep_23 = sep_23.groupby(['Identification ID','Model Name','Location','Period','Output Color'])['Impressions'].sum().reset_index()
gr_oct_23 = oct_23.groupby(['Identification ID','Model Name','Location','Period','Output Color'])['Impressions'].sum().reset_index()
gr_nov_23 = nov_23.groupby(['Identification ID','Model Name','Location','Period','Output Color'])['Impressions'].sum().reset_index()
gr_dec_23 = des_23.groupby(['Identification ID','Model Name','Location','Period','Output Color'])['Impressions'].sum().reset_index()
gr_jan_24 = jan_24.groupby(['Identification ID','Model Name','Location','Period','Output Color'])['Impressions'].sum().reset_index()
gr_feb_24 = feb_24.groupby(['Identification ID','Model Name','Location','Period','Output Color'])['Impressions'].sum().reset_index()
gr_mar_24 = mar_24.groupby(['Identification ID','Model Name','Location','Period','Output Color'])['Impressions'].sum().reset_index()
gr_apr_24 = apr_24.groupby(['Identification ID','Model Name','Location','Period','Output Color'])['Impressions'].sum().reset_index()
gr_may_24 = may_24.groupby(['Identification ID','Model Name','Location','Period','Output Color'])['Impressions'].sum().reset_index()
gr_jun_24 = jun_24.groupby(['Identification ID','Model Name','Location','Period','Output Color'])['Impressions'].sum().reset_index()
gr_jul_24 = jul_24.groupby(['Identification ID','Model Name','Location','Period','Output Color'])['Impressions'].sum().reset_index()

In [22]:
gr_sep_23.to_excel(
    "D:\\Astragraphia\\BO1\\Pelindo\\Zweite Entwicklung\\rekap_meter_23-24_temp.xlsx",
    sheet_name = 'Sep 2023'
)

In [23]:
path = r"D:\\Astragraphia\\BO1\\Pelindo\\Zweite Entwicklung\\rekap_meter_23-24_temp.xlsx"
with pd.ExcelWriter(path, engine='openpyxl') as writer:
    gr_sep_23.to_excel(writer, sheet_name='Sep 2023')
    gr_oct_23.to_excel(writer, sheet_name='Okt 2023')
    gr_nov_23.to_excel(writer, sheet_name='Nov 2023')
    gr_dec_23.to_excel(writer, sheet_name='Des 2023')
    gr_jan_24.to_excel(writer, sheet_name='Jan 2024')
    gr_feb_24.to_excel(writer, sheet_name='Feb 2024')
    gr_mar_24.to_excel(writer, sheet_name='Mar 2024')
    gr_apr_24.to_excel(writer, sheet_name='Apr 2024')
    gr_may_24.to_excel(writer, sheet_name='Mei 2024')
    gr_jun_24.to_excel(writer, sheet_name='Jun 2024')
    gr_jul_24.to_excel(writer, sheet_name='Jul 2024')

In [24]:
comp = rc.mergeData(
    gr_sep_23,
    gr_oct_23,
    gr_nov_23,
    gr_dec_23,
    gr_jan_24,
    gr_feb_24,
    gr_mar_24,
    gr_apr_24,
    gr_may_24,
    gr_jun_24
)

comp = rc.mergeData(comp, gr_jul_24)

In [25]:
comp['Period'].unique()

array(['Sep 2023', 'Okt 2023', 'Nov 2023', 'Des 2023', 'Jan 2024',
       'Feb 2024', 'Mar 2024', 'Apr 2024', 'Mei 2024', 'Jun 2024',
       'Jul 2024'], dtype=object)

In [26]:
comp['Period'].unique()
comp_piv = pd.pivot_table(
    data=comp,
    index=['Model Name','Identification ID','Location'],
    columns=['Period','Output Color'],
    values='Impressions',
    aggfunc=sum
).fillna(0)
comp_piv
comp_piv.to_excel(
    "D:\\Astragraphia\\BO1\\Pelindo\\Zweite Entwicklung\\Compiled_Report_temp_23.xlsx"
)